### ISSUE TITLE
API Key Disclosed

### ISSUE THREAD

**Issue by Aniruddhan15** [keerthikrish10/AI-POWERED-TRAVEL-ITENARY-APP-using-GEMINI-API-integration-with-python-#1]
Respected Keerthi Krishna,
You have put your API Key inside this project in the ipynb file.
Github/ any opensource platforms doesnt allow you to share your api key.
It gives you a warning symbol for it via email.
Please remove and use a **".env"** file and **"python-dotenv"**

**Comment by keerthikrish10** [comment]
ok

**Comment by Aniruddhan15** [comment]
Amzing Sir! Lets exchange and learn. Hope to see you one day in real life!
